---
title: "W2 Map"
author: "WR"
date: "4/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
#load data
library(leaflet)
covid <- read.csv("w2-covid.csv")
```

### Confirmed Coronavirus Cases by April 20, 2020
```{r, echo=FALSE, message=FALSE, fig.align='center'}
d<-"x04.20.20"
nonzeros <- covid[which(covid[,c(d)]!=0),]
cases <- nonzeros[,c(d)]
nonzeros %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight=0,radius=cases*5,color="red",
               label=paste(nonzeros$province.state,":",
               format(cases,big.mark = ",")), 
               fillOpacity = 0.5)
```
<span style="font-size:12px">Data Source: CSSE at Johns Hopkins University</span><br/> <span style="font-size:12px">[time_series_covid19_confirmed_US.csv](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series),
[time_series_covid19_confirmed_global_iso3_regions.csv](https://data.humdata.org/dataset/novel-coronavirus-2019-ncov-cases)</span>
